### ISSUE TITLE
Relaunch using the same parameters causes multiple executions

### ISSUE THREAD

**Issue by greenscar** [ansible/awx#1150]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - UI

##### SUMMARY

When I rerun a failed Workflow job, it tries to execute each stage twice, in parallel
##### ENVIRONMENT
* AWX version: 1.0.3
* AWX install method: docker
* Ansible version:  2.4.1
* Operating System: Ubuntu
* Web Browser: Chrome, Opera, Safari

##### STEPS TO REPRODUCE

Create 2 jobs. Ensure one of them will fail.
Create a workflow job using these 2 jobs.
The job which will fail is first to execute.
Run the workflow job.
After it fails, go to the job list and click the rocket to rerun.

##### EXPECTED RESULTS
The job should rerun the failed instance.

##### ACTUAL RESULTS

The job attempts to rerun twice in parallel.

##### ADDITIONAL INFORMATION
![image](https://user-images.githubusercontent.com/4122160/35932656-19869c7c-0bed-11e8-93c4-2b4f88e57457.png)

**Comment by jaredevantabor** [comment]
Tagging API

**Comment by ryanpetrello** [comment]
@greenscar are you still able to reproduce this?  If so, can you provide some clarity?

Can you share the workflow editor where you've observing this bug?  I'd like to see how you've connected the Job Templates.

> Run the workflow job. After it fails, go to the job list and click the rocket to rerun.

Relaunch what? The job in the workflow job, or the workflow job itself?

**Comment by ryanpetrello** [comment]
I'm having trouble reproducing this.  Here's a Workflow I created.  The first Job Template, `Demo Job Template`, will always fail:

![screen shot 2018-04-26 at 4 09 24 pm](https://user-images.githubusercontent.com/214912/39329421-3d3d6dc8-496c-11e8-80d0-d704c3629d09.png)

When I ran the workflow, it did fail, and did not run the second Job Template:

![screen shot 2018-04-26 at 4 10 47 pm](https://user-images.githubusercontent.com/214912/39329475-6c294710-496c-11e8-859f-503acf89ef04.png)

This list of jobs shows the failed workflow and the first Job Template that failed:

![screen shot 2018-04-26 at 4 11 25 pm](https://user-images.githubusercontent.com/214912/39329503-82b20788-496c-11e8-869e-cc5c98cde7e7.png)

When I relaunched the Workflow Job from this UI, the workflow did _not_ create duplicate parallel jobs; the behavior was the same as the initial Workflow launch:

![screen shot 2018-04-26 at 4 13 02 pm](https://user-images.githubusercontent.com/214912/39329565-b55d4256-496c-11e8-885e-9fe298089ee0.png)

![screen shot 2018-04-26 at 4 13 54 pm](https://user-images.githubusercontent.com/214912/39329601-d62177dc-496c-11e8-9e8a-f541f23d93a9.png)

**Comment by ryanpetrello** [comment]
Closing this - @greenscar let us know if you're still able to reproduce this issue in the latest version of awx, or if you have additional details that can shed light on reproducing what you saw.

**Comment by greenscar** [comment]
@ryanpetrello : With 1.0.6 I restarted a failed job and the problem of branching appears resolved. Thanks.

**Comment by greenscar** [comment]
@ryanpetrello : Apparently I was wrong. I reran & had 2. It failed. I reran again. Now I see 
![screen shot 2018-05-31 at 1 49 56 pm](https://user-images.githubusercontent.com/4122160/40807609-a5a10608-64d9-11e8-998d-d784d595a441.png)

**Comment by wwitzel3** [comment]
This is fixed upstream and should land back in AWX soon.

**Comment by sumkincpp** [comment]
Issue is still present in AWX 1.0.6/1.0.6.23

**Comment by itdependsnetworks** [comment]
Checking in on status, about to test with latest devel version, but seems as per previous comment may not be done.

**Comment by itdependsnetworks** [comment]
I am seeing the subtle difference here. It must meet the following conditions:

- "ask_variables_on_launch": true is set
- You actually sent in variables.

You only need one template, but send extra_vars. I have tested with docker latest image and it is still there.


@ryanpetrello @wwitzel3 Can we re-open this?

**Comment by ryanpetrello** [comment]
@sumkincpp @itdependsnetworks we have a downstream change that will be merging soon that should resolve this - as it currently stands, it's still broken in 1.0.6.

**Comment by itdependsnetworks** [comment]
@ryanpetrello any chance you can provide me the patch, or let me know what to refer for my customer to get access on their tower instance?

**Comment by ryanpetrello** [comment]
@itdependsnetworks the patch is pretty simple, and is really only applicable to the latest awx and an upcoming version of Tower.  That said, I haven't personally tested it on awx.  If you want to give it a whirl anyways, try changing:

https://github.com/ansible/awx/blob/devel/awx/main/models/workflow.py#L289

from:

```python
def create_relaunch_workflow_job(self):
    new_workflow_job = self.copy_unified_job()
    new_workflow_job.copy_nodes_from_original(original=self)
    return new_workflow_job
```

...to...

```python
def create_relaunch_workflow_job(self):
    new_workflow_job = self.copy_unified_job()
    if self.workflow_job_template is None:
        new_workflow_job.copy_nodes_from_original(original=self)
    return new_workflow_job
```

**Comment by itdependsnetworks** [comment]
Awesome!! Works great. You are a scholar, gentleman, and an acrobat.

**Comment by itdependsnetworks** [comment]
@wwitzel3 why close if not fixed? Unless I missed the PR that was associated with it.

**Comment by wwitzel3** [comment]
Because we have a PR upstream (the diff that @ryanpetrello shared) that fixes the issue. And someone can use the diff here to manually patch in the meantime. So for purposes of tracking work that needs to be done, there is none. The work is done and will land shortly.

**Comment by sumkincpp** [comment]
Wow, great work, fixed at least in latest **1.0.6.49**
