### ISSUE TITLE
AWX 3 using wrong python libs

### ISSUE THREAD

**Issue by AdrianDutu** [ansible/awx#3267]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

 - UI
 - Installer

##### SUMMARY
Playbook running from AWX UI fails, but running ansible-playbook inside awx_celery with the same play works. My playbook is looking like this:

`---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Import inventory   
      shell: "awx-manage inventory_import --source=hosts --inventory-name=bwin --overwrite"
      args:
        chdir: /var/lib/awx/shared`

If I do docker exec -it awx_celery /bin/bash, then cd /var/lib/awx/projects/_14__awx and run here ansible-playbook awx-inv-sync.yml, it works.
If I go to the AWX UI and run a job that uses this playbook this is what i get:

Playbook output:
`TASK [Import inventory] ********************************************************
task path: /var/lib/awx/projects/_14__awx/plays/awx-inventory-sync.yml:13
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: awx
<127.0.0.1> EXEC /bin/sh -c 'echo ~awx && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1550598400.14-158561699519226 `" && echo ansible-tmp-1550598400.14-158561699519226="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1550598400.14-158561699519226 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
<127.0.0.1> PUT /var/lib/awx/.ansible/tmp/ansible-local-3Krrd2O/tmpw6Iqa5 TO /var/lib/awx/.ansible/tmp/ansible-tmp-1550598400.14-158561699519226/AnsiballZ_command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1550598400.14-158561699519226/ /var/lib/awx/.ansible/tmp/ansible-tmp-1550598400.14-158561699519226/AnsiballZ_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /var/lib/awx/.ansible/tmp/ansible-tmp-1550598400.14-158561699519226/AnsiballZ_command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-tmp-1550598400.14-158561699519226/ > /dev/null 2>&1 && sleep 0'
fatal: [127.0.0.1]: FAILED! => {
    "changed": true, 
    "cmd": "awx-manage inventory_import --source=/var/lib/awx/shared/hosts --inventory-name=bwin --overwrite", 
    "delta": "0:00:00.125621", 
    "end": "2019-02-19 17:46:40.547984", 
    "invocation": {
        "module_args": {
            "_raw_params": "awx-manage inventory_import --source=/var/lib/awx/shared/hosts --inventory-name=bwin --overwrite", 
            "_uses_shell": true, 
            "argv": null, 
            "chdir": null, 
            "creates": null, 
            "executable": "/bin/bash", 
            "removes": null, 
            "stdin": null, 
            "warn": true
        }
    }, 
    "msg": "non-zero return code", 
    "rc": 1, 
    "start": "2019-02-19 17:46:40.422363",`

Stderr:

`Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/bin/awx-manage", line 4, in <module>
    import re
  File "/usr/lib64/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'`

##### ENVIRONMENT
* AWX version: 3.0.1
* AWX install method: kubernetes
* Ansible version:  2.7
* Operating System: CentOS 7

##### STEPS TO REPRODUCE

1. Have a inventory file somewhere in awx_celery and use a playbook that will use awx_manage to import it to awx (example in my summary above)
2. Run the playbook from AWX UI

##### EXPECTED RESULTS

Play should work and inventory should be imported

##### ACTUAL RESULTS

Play fails with the errors mentioned above. 

##### ADDITIONAL INFORMATION

What is weird to me is that there is a python 3.6 lib related error. From what I knowm awx 3 uses python 3 but ansible should still be using 2.7. So somehow the libs get mixed up?

**Comment by ryanpetrello** [comment]
@AdrianDutu,

This is a bug in the `enum34` library:
https://bitbucket.org/stoneleaf/enum34/issues/19/enum34-isnt-compatible-with-python-36

```python
Traceback (most recent call last):
File "/var/lib/awx/venv/awx/bin/awx-manage", line 4,
    in <module> import re File "/usr/lib64/python3.6/re.py", line 142,
    in <module> class RegexFlag(enum.IntFlag): AttributeError: module 'enum' has no attribute 'IntFlag'`
```

This is usually a sign that your awx virtualenv mistakenly has `enum34` installed (`enum34` is a python2 *only* packaged intended to act as a _polyfill_ for the `enum` module in python3 - many libraries in the python2 ecosystem depend on it as a source of an `enum`-like data structure).  Have you installed any custom libraries into `/var/lib/awx/venv` ?

I'm guessing if you do this:

```
~ /var/lib/awx/venv/awx/bin/pip uninstall enum34
```

...then things will start working, but I'd like to understand _how_ you got into this state so we can try to prevent it.

**Comment by AdrianDutu** [comment]
@ryanpetrello 
That is the thing. It's a fresh install. I have not installed anything custom. 
My inventory looks like this:

>[tower]
 hostname1.**** ansible_connection=local
dockerhub_base=ansible
kubernetes_context=awx-prod
kubernetes_namespace=awx
tiller_namespace=kube-system
awx_task_hostname=awx
awx_web_hostname=awxweb
host_port=80
pg_hostname=******
pg_username=awx
pg_password=******
pg_database=awx
pg_port=5432
rabbitmq_password=******
rabbitmq_erlang_cookie=********
rabbitmq_enable_manager=True
admin_user=admin
admin_password=******
secret_key=********

The only custom thing I did was add some mount points in installer/roles/kubernetes/templates/deployment.yml.j2 since ca_trust_dir is ignored for kubernetes installs and I needed certificates for AD integration.

**Comment by ryanpetrello** [comment]
@AdrianDutu can you share the output of this command:

`/var/lib/awx/venv/awx/bin/pip freeze`

**Comment by AdrianDutu** [comment]
@ryanpetrello 

> bash-4.2# /var/lib/awx/venv/awx/bin/pip freeze
amqp==2.3.2
ansiconv==1.0.0
appdirs==1.4.2
asgi-amqp==1.1.3
asgiref==1.1.2
asn1crypto==0.24.0
attrs==17.4.0
autobahn==18.3.1
Automat==0.6.0
awx==3.0.1.0
baron==0.6.6
billiard==3.5.0.4
boto==2.47.0
celery==4.2.1
cffi==1.11.5
channels==1.1.8
constantly==15.1.0
cryptography==2.3.1
daphne==1.3.0
defusedxml==0.5.0
Django==1.11.16
django-auth-ldap==1.7.0
django-cors-headers==2.4.0
django-crum==0.7.2
django-extensions==2.0.0
django-jsonfield==1.0.1
django-oauth-toolkit==1.1.3
django-pglocks==1.0.2
django-polymorphic==2.0.2
django-qsstats-magic==0.7.2
django-radius==1.3.3
django-solo==1.1.3
django-split-settings==0.3.0
django-taggit==0.22.2
djangorestframework==3.7.7
djangorestframework-yaml==1.0.3
docutils==0.14
future==0.16.0
hyperlink==18.0.0
idna==2.6
incremental==17.5.0
inflect==0.2.5
ipaddress==1.0.19
irc==16.2
isodate==0.6.0
jaraco.classes==1.4.3
jaraco.collections==1.5.3
jaraco.functools==1.17
jaraco.itertools==2.1.1
jaraco.logging==1.5.1
jaraco.stream==1.1.2
jaraco.text==1.10
Jinja2==2.10
jsonbfield==0.1.0
jsonpickle==0.9.6
jsonschema==2.6.0
kombu==4.2.1
lxml==4.2.3
Markdown==2.6.11
MarkupSafe==1.0
more-itertools==4.1.0
msgpack-python==0.5.5
netaddr==0.7.19
oauthlib==2.0.6
ordereddict==1.1
pexpect==4.6.0
pkgconfig==1.4.0
psutil==5.4.3
psycopg2==2.7.3.2
ptyprocess==0.5.2
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycparser==2.18
pygerduty==0.37.0
PyJWT==1.6.0
pyOpenSSL==19.0.0
pyparsing==2.2.0
pyrad==2.1
PySocks==1.6.8
python-dateutil==2.7.2
python-ldap==3.1.0
python-logstash==0.4.6
python-memcached==1.59
python-radius==1.0
python3-openid==3.1.0
python3-saml==1.4.0
pytz==2018.5
PyYAML==3.12
redbaron==0.6.3
requests==2.15.1
requests-futures==0.9.7
requests-oauthlib==0.8.0
rply==0.7.5
service-identity==17.0.0
simplejson==3.13.2
six==1.11.0
slackclient==1.1.2
social-auth-app-django==2.1.0
social-auth-core==3.0.0
tacacs-plus==1.0
tempora==1.10
twilio==6.10.4
Twisted==17.9.0
txaio==2.9.0
typing==3.6.4
uWSGI==2.0.17
uwsgitop==0.10
vine==1.2.0
websocket-client==0.47.0
xmlsec==1.3.3
zope.interface==4.4.3

**Comment by ryanpetrello** [comment]
@AdrianDutu have you installed a python package into your *global* site-packages that included `enum34`?

`~ sudo pip freeze | grep enum`

**Comment by AdrianDutu** [comment]
@ryanpetrello I didn't install anything. But the output of that command is:
bash-4.2# pip freeze | grep enum
enum34==1.0.4

**Comment by ryanpetrello** [comment]
@AdrianDutu if you `pip uninstall enum34` from your global site-packages, does the problem go away?

**Comment by AdrianDutu** [comment]
@ryanpetrello No, it doesn't.

**Comment by AdrianDutu** [comment]
If I try exactly the same steps on 2.1.2, I get a totally different error:

> Traceback (most recent call last):
  File "/usr/bin/awx-manage", line 9, in <module>
    load_entry_point('awx==2.1.2.0', 'console_scripts', 'awx-manage')()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 134, in manage
    prepare_env()
  File "/usr/lib/python2.7/site-packages/awx/__init__.py", line 89, in prepare_env
    if not settings.DEBUG: # pragma: no cover
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/var/lib/awx/venv/awx/lib/python2.7/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/python2.7/site-packages/awx/settings/production.py", line 107, in <module>
    raise ImproperlyConfigured(msg)
django.core.exceptions.ImproperlyConfigured: No AWX configuration found at /etc/tower/settings.py.
Define the AWX_SETTINGS_FILE environment variable to specify an alternate path.

I was expecting not to get the enum34 error since it's not using python3 here but this other error doesn't make sense since the settings.py file is there.

**Comment by ryanpetrello** [comment]
After you run:

```
~ pip uninstall enum34
```

...does:

```
pip freeze | grep enum
```

...still show the `enum34` package?

**Comment by kpocius** [comment]
Got the same issue when running AWX in Docker.

Running:
```
/var/lib/awx/venv/awx/bin/pip freeze | grep enum
```
or
```
pip3 freeze | grep enum
```
returns no results.

Running:
```
pip freeze | grep enum
```
Does show that `enum34` is installed, which makes sense, since it's Python 2, but uninstalling it doesn't fix the issue.

**Comment by AdrianDutu** [comment]
@ryanpetrello it does not show anymore.

**Comment by AdrianDutu** [comment]
@ryanpetrello I tried the following:

```bash
source /var/lib/awx/venv/ansible/bin/activate
pip freeze | grep enum
enum34==1.1.6
```

So the venv still had that. 

I also tried (before uninstalling enum from the venv) to do a source then run my playbook and it was running fine from the terminal. Something doesn't add up here, same venv from terminal and awx, terminal works, awx doesn't.

Let's call it a small success though, now the play doesn't give that enum exception in AWX UI, but it throws another exception:

```python
File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/concurrent/futures/_base.py", line 414
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```
I edited _base.py and commented that line since it's just an exception throw, and now I get another error:

```python
"/var/lib/awx/venv/awx/lib64/python3.6/site-
packages/django/core/management/__init__.py", line 338, in execute
django.setup()   File "/var/lib/awx/venv/awx/lib64/python3.6/site-
packages/django/__init__.py", line 22, in setup
configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)   File
"/var/lib/awx/venv/awx/lib64/python3.6/site-packages/django/utils/log.py", line
75, in configure_logging     logging_config_func(logging_settings)   File
"/usr/lib64/python3.6/logging/config.py", line 795, in dictConfig
dictConfigClass(config).configure()   File
"/usr/lib64/python3.6/logging/config.py", line 541, in configure     'formatter
%r: %s' % (name, e)) ValueError: Unable to configure formatter 'json': Cannot
resolve 'awx.main.utils.formatters.LogstashFormatter': No module named 'error'
```
This is looking hopeless...
Should i open another bug for these issues?

**Comment by ryanpetrello** [comment]
@AdrianDutu are you using the official images, or building your own?  Are you building your own Python?  Something is fishy here, because this *is* valid python2 syntax:

```
File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/concurrent/futures/_base.py", line 414
    raise exception_type, self._exception, self._traceback
                        ^
SyntaxError: invalid syntax
```

...but it *is* invalid Python3 syntax.

For one of these failing jobs, can you visit `/api/v2/jobs/N/` and share the `job_args` and `job_env` values?

**Comment by AdrianDutu** [comment]
@ryanpetrello I am using the official images. The only thing I changed was to add some mount points to the kubernetes deployment. I didn't mess with anything else.

**Comment by cippaciong** [comment]
I'm having the same problem described by @AdrianDutu (almost identical setup but I'm using docker-compose instead of Kubernetes).
I don't know if this is a relevant info but the problem comes up on a playbook where I added `127.0.0.1 ansible_python_interpreter='/usr/bin/env python3'` in the inventory

**Comment by arnaudsaric** [comment]
Ran into the issue as well using docker-compose.

There is indeed a weird mix of python 2.7 and 3.6: by default the `/var/lib/awx/venv/ansible` env uses python2.7 (and has the `enum34` package), and `/var/lib/awx/venv/awx` uses python3.6.

Project updates seem to use both environments at the same time: they are launched using `/var/lib/awx/venv/awx/bin/ansible-playbook` (therefore python3.6), but have in their env `PYTHONPATH=/var/lib/awx/venv/ansible/lib/python2.7/site-packages:/var/lib/awx/venv/awx/lib64/python3.6/site-packages/awx/lib:` => that is how you end up using the `enum34` package from the `ansible` env instead of the standard python3.6 `enum` from the `awx` env.

Rebuilding an `ansible` virtualenv in python3.6 did fix the issue for me.

**Comment by ryanpetrello** [comment]
@arnaudsaric @cippaciong @AdrianDutu ultimately, this comes down to an issue where `enum34` incorrectly installs in environments where it's not needed (python3), and pollutes the `enum` namespace with a package that doesn't work in python3 (and we have little control over it).  If this is causing you pain, please see my comment and chime in on this issue:

https://bitbucket.org/stoneleaf/enum34/pull-requests/7/setuppy-dont-shadow-builtin-enum-package/diff

**Comment by arnaudsaric** [comment]
@ryanpetrello I don't think the PR you linked would change anything to the issue. The `enum34` package is installed in the `ansible` venv, which is built using python2.7. This PR only changes stuff for python >= 3.4.

The issue is this venv then gets used with a python3.6 interpreter...

**Comment by ryanpetrello** [comment]
@arnaudsaric I'll take a look soon and see if I can reproduce something.

**Comment by AlKult** [comment]
Hi,

New to this thread. I built a brand new docker-compose awx image (official) just earlier this week, and been banging my head against the wall ever since. Having read this thread, I seem to have the exact same issue and tried similar troubleshooting techniques, so I don't really have anything to contribute in terms of logs or troubleshooting. Therefore, just wondering if devs have made any further progress with the issue?

Thanks!

Best regards,
Albert.

**Comment by kkniffin** [comment]
Similar error when trying to run the inventory script from: https://gist.github.com/tkjaer/6d606b14d4413f7101b6eb6cc28c9e22

**Comment by ryanpetrello** [comment]
I'm able to reproduce a version of this with project updates in the dev environment by setting the default system as Python3:

```
rm /usr/bin/python
ln -s /usr/bin/python3 /usr/bin/python
```

![image](https://user-images.githubusercontent.com/214912/56166231-0b92f880-5fa3-11e9-89ea-f8ca592f03ff.png)

It seems to have something to do with the usage of `ansible_connection: local` and ansible using the _incorrect_ Python interpreter when `/usr/bin/python` is actually python3.

**Comment by ryanpetrello** [comment]
I _think_ this might be a symptom of https://github.com/ansible/ansible/issues/44173.  Digging...

**Comment by ryanpetrello** [comment]
This _feels like_ an ansible bug on systems that have python3 as the default system Python.

```shell
bash-4.2$ python --version
Python 3.6.6
bash-4.2$ virtualenv -p `which python2` py2
bash-4.2$ source ./py2/bin/activate
(py2) bash-4.2$ pip install ansible
(py2) bash-4.2$ PYTHONPATH=/tmp/py2/lib/python2.7/site-packages/ ansible-playbook ./example.yml -c local -i localhost, -vvv
ansible-playbook 2.7.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/tmp/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/py2/lib/python2.7/site-packages/ansible
  executable location = /tmp/py2/bin/ansible-playbook
  python version = 2.7.5 (default, Apr  9 2019, 14:30:50) [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]
Using /etc/ansible/ansible.cfg as config file
Parsed localhost, inventory source with host_list plugin

PLAYBOOK: example.yml *********************************************************************************************************************************************************************************************************************
1 plays in ./example.yml

PLAY [all] ********************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [file] *******************************************************************************************************************************************************************************************************************************
task path: /tmp/example.yml:8
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: awx
<localhost> EXEC /bin/sh -c 'echo ~awx && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/.ansible/tmp/ansible-tmp-1555369722.59-140154791303941 `" && echo ansible-tmp-1555369722.59-140154791303941="` echo /tmp/.ansible/tmp/ansible-tmp-1555369722.59-140154791303941 `" ) && sleep 0'
Using module file /tmp/py2/lib/python2.7/site-packages/ansible/modules/files/file.py
<localhost> PUT /tmp/.ansible/tmp/ansible-local-15117hV09TB/tmpLvylIG TO /tmp/.ansible/tmp/ansible-tmp-1555369722.59-140154791303941/AnsiballZ_file.py
<localhost> EXEC /bin/sh -c 'chmod u+x /tmp/.ansible/tmp/ansible-tmp-1555369722.59-140154791303941/ /tmp/.ansible/tmp/ansible-tmp-1555369722.59-140154791303941/AnsiballZ_file.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /tmp/.ansible/tmp/ansible-tmp-1555369722.59-140154791303941/AnsiballZ_file.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /tmp/.ansible/tmp/ansible-tmp-1555369722.59-140154791303941/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/.ansible/tmp/ansible-tmp-1555369722.59-140154791303941/AnsiballZ_file.py", line 113, in <module>
    _ansiballz_main()
  File "/tmp/.ansible/tmp/ansible-tmp-1555369722.59-140154791303941/AnsiballZ_file.py", line 16, in _ansiballz_main
    import base64
  File "/usr/lib64/python3.6/base64.py", line 9, in <module>
    import re
  File "/usr/lib64/python3.6/re.py", line 142, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/.ansible/tmp/ansible-tmp-1555369722.59-140154791303941/AnsiballZ_file.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/tmp/.ansible/tmp/ansible-tmp-1555369722.59-140154791303941/AnsiballZ_file.py\", line 16, in _ansiballz_main\n    import base64\n  File \"/usr/lib64/python3.6/base64.py\", line 9, in <module>\n    import re\n  File \"/usr/lib64/python3.6/re.py\", line 142, in <module>\n    class RegexFlag(enum.IntFlag):\nAttributeError: module 'enum' has no attribute 'IntFlag'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
	to retry, use: --limit @/tmp/example.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

Here's `example.yml`:

```yml
---

- hosts: all
  gather_facts: false
  vars:
    file_name: '/tmp/test'
  tasks:
    - file:
        path: '{{file_name}}'
        state: touch
```

Maybe there's a gap in my Python/virtualenv/site knowledge here, but it seems _really odd_ that Python/Ansible would attempt to import _anything_ from `/usr/lib64/python3.6/`.

**Comment by ryanpetrello** [comment]
Okay.

I think this actually comes down to an ansible limitation related to `connection: local`:

https://docs.ansible.com/ansible/latest/inventory/implicit_localhost.html

In order for this to work in systems with split Python versions (`/usr/bin/python` is py3, the ansible venv is py2), you've got to explicitly specify `ansible_python_interpreter: /path/to/python2` as a hostvar so that local connections work properly (and don't use `/usr/bin/python`, which is py3).

@AdrianDutu (and others):

If you add this as a hostvars on your local host(s), does it help?

`ansible_python_interpreter: '{{ ansible_playbook_python }}'`

A few of you (including me) have mentioned that you're seeing similar issues when running project updates.  I've pushed a pull request that should address _that_ issue:

https://github.com/ansible/awx/pull/3715

**Comment by ryanpetrello** [comment]
Also @AdrianDutu if this doesn't work for you, instead of:

`connection: local`

Could you try:

`delegate_to: 127.0.0.1`

**Comment by ryanpetrello** [comment]
I've merged in https://github.com/ansible/awx/pull/3715, which should help address the issue for those of you facing this with project updates.

For anybody else here running Python3 as their system Python with a Python2 virtualenv (custom or not), make sure any host with `ansible_connection: local` *also* specifies `ansible_python_interpreter: '{{ ansible_playbook_python }}'`.

See: https://docs.ansible.com/ansible/latest/inventory/implicit_localhost.html

**Comment by mlninc** [comment]
I was experiencing this error in AWX for over a week: `AttributeError: 'HTTPError' object has no attribute 'headers`
Setting host vars as advised by @ryanpetrello solved my problem
solution: 
 `  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'`

**Comment by yagashiraevil** [comment]
![image](https://user-images.githubusercontent.com/26820733/75951043-bcacc500-5ecc-11ea-966b-4cb04414b8a8.png)
I am getting this when runing on remote machine i just install awx 9.2

**Comment by wilfil** [comment]
> ![image](https://user-images.githubusercontent.com/26820733/75951043-bcacc500-5ecc-11ea-966b-4cb04414b8a8.png)
> I am getting this when runing on remote machine i just install awx 9.2

I have the same problem after upgrading my tower to the latest version (3.6).

**Comment by vijayreddiar** [comment]
Issue persists in Ansible Tower 3.6.2 having Ansible Engine 2.9.3 even if we use the variable `ansible_python_interpreter: '{{ ansible_playbook_python }}'`

> Traceback (most recent call last):
>   File "/usr/bin/awx-manage", line 4, in <module>
>     import re
>   File "/opt/rh/rh-python36/root/usr/lib64/python3.6/re.py", line 142, in <module>
>     class RegexFlag(enum.IntFlag):
> AttributeError: module 'enum' has no attribute 'IntFlag'

**Comment by iabughosh** [comment]
Same problem for me when using module 'docker_volume' in awx docker-compose version.

**Comment by dimaslv** [comment]
Had same problem, when trying to run pip3 from under the awx, running on python2.
The cause appeared to be because of the PYTHONPATH environment variable, which was set by awx to first include python2.7/site-packages (which contains enum34, needed for python2) and after that python3.6/site-packages.
Workaround is to run "pyton3 -E -m pip" to ignore environment variable or to reset same variable in the playbook with:
```
environment:
  PYTHONPATH: ""
```

**Comment by MuriloChianfa** [comment]
as @cippaciong say, im only put this `ansible_python_interpreter='/usr/bin/env python3'` in hosts without support of python-apt and runs prettrily,, very thx,
