### ISSUE TITLE
Ansible 2.3 cannot run the install.yml playbook due to include_tasks

### ISSUE THREAD

**Issue by dleehr** [ansible/awx#532]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
INSTALL.md lists Ansible 2.3+ as required version, but `install.yml` playbook fails to run with Ansible 2.3.0.0. 2.4.1.0 worked.

##### ENVIRONMENT
* AWX version: 0876d7825cd0ce28a9e2564325f3e2b70553a930
* AWX install method: Docker for Mac
* Ansible version:  2.3.0.0
* Operating System: macOS 10.12.6
* Web Browser: Safari

##### STEPS TO REPRODUCE

1. Install ansible 2.3.3.0
2. Clone github.com/ansible/awx
3. cd awx/install
4. ansible-playbook -i inventory install.yml 

##### EXPECTED RESULTS

Documented version of ansible can run the playbook.

##### ACTUAL RESULTS

ansible 2.3 fails to load the playbook, because [include_tasks](https://docs.ansible.com/ansible/2.4/include_tasks_module.html) is referenced in the playbook but not available until 2.4.

```
$ ansible --version
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]

$ ansible-playbook -i inventory install.yml 
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/Users/dcl9/Code/ansible/awx/installer/check_vars/tasks/main.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- include_tasks: check_openshift.yml
  ^ here


The error appears to have been in '/Users/dcl9/Code/ansible/awx/installer/check_vars/tasks/main.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- include_tasks: check_openshift.yml
  ^ here
```

##### ADDITIONAL INFORMATION

Upgrading my local copy of ansible to 2.4.1.0 fixes the issue:

```
$ ansible --version
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/Users/dcl9/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.1.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]


$ ansible-playbook -i inventory install.yml 

PLAY [Build and deploy AWX] *******************************************************************************************************

TASK [check_vars : include_tasks] *************************************************************************************************
skipping: [localhost]
...
```

**Comment by matburt** [comment]
Fixed

**Comment by aabuhasna-zz** [comment]
Hi,
I am facing the same issue while using version 2.4.2.0

**Comment by asziranyi** [comment]
I confirm that the issue gone in `2.4.3.0`.

**Comment by aabuhasna** [comment]
Hi, the issue is not fixed yet completely. now its buggy (sometimes it work). this is Ansible information I have

> ansible 2.4.3.0
>   config file = /etc/ansible/ansible.cfg
>   configured module search path = [u'/home/aabuhasna/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
>   ansible python module location = /usr/lib/python2.7/site-packages/ansible
>   executable location = /usr/bin/ansible
>   python version = 2.7.14 (default, Feb 17 2018, 10:42:17) [GCC 7.3.1 20180130 (Red Hat 7.3.1-2)]
>

**Comment by aabuhasna-zz** [comment]
Thanks. everything is working fine. now

**Comment by shahidkarimi** [comment]
How this was fixed? @aabuhasna ?

**Comment by sidrai33** [comment]
why do i not see awx/install folder ?

**Comment by sidrai33** [comment]
can someone help here.. I am new to ansible... and cloned github.com/ansible/awx
but i dont see awx/install dir and install.yml file.

**Comment by shahidkarimi** [comment]
@sidrai33 for this include_task issue, it worked for me when changed to include: "task.yml"

**Comment by ryanpetrello** [comment]
@sidrai33 @shahidkarimi

`./installer` is gone from `devel` (and the next major version of AWX, which is not yet released):

https://groups.google.com/g/awx-project/c/47MjWSUQaOc/m/bCjSDn0eBQAJ

It still exists in the current stable version of AWX (17.1.0):

https://github.com/ansible/awx/tree/17.1.0/installer
