### ISSUE TITLE
Expose the SCM Branch name in the playbook environment

### ISSUE THREAD

**Issue by Malizor** [ansible/awx#8429]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Today if I launch a job and put `foobar` in the "SCM Branch" field, the corresponding commit hash is exposed as `awx_project_revision` but the proper human readable name of my branch/tag `foobar` remains inaccessible.

A use case to access this information is to put it in configuration files (eg. in a UI to document which version of the platform was deployed). Many more can be envisioned too.

I see two paths for implementation:
* Change the `awx_project_revision` content to keep the SCM Branch as it was in the input (stop turning it into a hash)
* Expose this into a variable of its own, like `awx_project_scm_branch`

**Comment by jakemcdermott** [comment]
Thought this was ui related but on second look it isn't.

**Comment by kdelee** [comment]
The variable is now available. Put up a PR in the tower docs repo, so not going to close yet, but once the docs are in we can close.

**Comment by Malizor** [comment]
[This page](https://docs.ansible.com/ansible-tower/latest/html/userguide/job_templates.html) seems to be the best candidate for adding the new variables documentation, but I can't find the related repository I should send a PR to.
Could someone point it to me?

**Comment by pmanno** [comment]
Hi,

Any update on this? I can't seem to find any info in the docs on it.

Also, I want to parameterize the requirements.yml file of the project, so I can update the project branch and all referenced roles. Should be able to just set

version: {{ scm_revision} }  in requirements.yml for that, right? 

Thanks,
Paul

**Comment by ckabalan** [comment]
+1 for this feature

Our use case is that we have playbooks that call other playbooks by name and many times we need to update multiple playbooks to create a new release. For example, we have a playbook that does the infrastructure provisioning phase of a VM deployment, then another that runs to configure the OS, then another that runs to test the resulting VM. Being able to call these by name using `tower_job_launch` with the SCM branch variable would allow us to say "VM Deploy feature-name" would also launch the templates "OS Configure feature-name" and "VM Test feature-name".

**Comment by joshebosh** [comment]
+1 for this feature... I have roles that do other git repos and would be nice to checkout branches based on the value in Project > SCM BRANCH box....

**Comment by wenottingham** [comment]
This has been fixed for a while. Closing.

**Comment by ryedin** [comment]
Not doubting that it's fixed, but it may not be documented well still. Wanted this feature, looked through the docs, googled, found this issue, back to looking through the docs.

Where is it documented what the variable name is for this? Is it this section: https://docs.ansible.com/ansible-tower/latest/html/userguide/jobs.html#job-branch-overriding?

Is the runtime variable name `scm_branch` as described in the first sentence? It's not clear here that this would be available to us at runtime using variables. Ie. are all highlighted/referenced "fields" in that page just assumed to be exposed as-is during runtime as variables we can consume?

**Comment by wenottingham** [comment]
The variable is `awx_project_scm_branch` and `awx_job_scm_branch`. It will be in the downstream docs at https://docs.ansible.com/ansible-tower/latest/html/userguide/job_templates.html once it's released in a downstream product. We could take a PR to docs/ in the AWX repo to have a section on job vars there.

**Comment by DE110283** [comment]
In which Tower version this will be available? Just tested in version 3.8.3 and it is still missing... (tower_job_scm_branch and tower_project_scm_branch not available in job run). Please add it in next 3.8.x tower version.

**Comment by gmisura** [comment]
+1
upvote
pretty please
