### ISSUE TITLE
CLI import of surveys does not work

### ISSUE THREAD

**Issue by AnnSopVier** [ansible/awx#8464]
##### ISSUE TYPE
 - Bug Report

##### ENVIRONMENT
* AWX version: 3.7.3.
* AWX install method: docker on linux
* Ansible version:  2.9.14
* Operating System: CentOS
* Web Browser: Firefox

##### STEPS TO REPRODUCE

Install Ansible and AWX and also CLI.  Copy the inventory and the survey.json file in /var/liv/awx/projects/00_NewCustomer of the docker container awx_web.
Enter the following commands via the CLI on the docker container awx_web:

- awx organizations create --name "trustedgate" 
awx users create --username "User" --is_superuser false --is_system_auditor false --password "password"
awx inventory create --name "00_NewCustomerSurvey_Inventory" --organization "trustedgate" 
awx projects create --name "00_NewCustomerSurvey_Project" --local_path @/var/lib/awx/projects/00_NewCustomer --organization "trustedgate"
awx job_templates create --name "00_NewCustomerSurvey_Template" --job_type run --inventory "00_NewCustomerSurvey_Inventory" --project "00_NewCustomerSurvey_Project" --playbook "00_NewCustomerSurvey.yaml" --survey_enabled true

All of these steps work and I can see the templates in the UI. 

If I now try to add a survey to the job_template (same result for both ways)  the survey is not added in the UI and I get the following feedback on the console.

awx job_templates delete --name "00_NewCustomerSurvey_Template" 

awx job_templates create --name "00_NewCustomerSurvey_Template" --job_type run --inventory "00_NewCustomerSurvey_Inventory" --project "00_NewCustomerSurvey_Project" --playbook "00_NewCustomerSurvey.yaml" --
survey_spec '{
  'description': 'A survey',
  'name': 'my survey'
  'spec': [{
      'index': 0,
      'question_name': 'What is your department',
      'required': False,
      'variable': 'department',
      'type': 'password',
      'max': 3
    }],
}' --survey_enabled=true

awx job_templates delete --name "00_NewCustomerSurvey_Template" 

awx job_templates modify --id "00_NewCustomerSurvey_Template" --survey_spec @/var/lib/awx/projects/00_NewCustomer/survey.json --survey_enable=true

The content of survey.json is:

{
  'description': 'A survey',
  'spec': [{
      'index': 0,
      'question_name': 'What is your department',
      'required': False,
      'variable': 'department',
      'type': 'password',
      'max': 3
    }],
  'name': 'my survey'
}

##### EXPECTED RESULTS

I would expect that in both cases the one-question-long survey would be imported to the UI  

##### ACTUAL RESULTS

The Job Template is created in both cases but no survey is added. The feedback from the console is in both cases the same (see screenshots attached)
![1](https://user-images.githubusercontent.com/72564826/97290255-974c3d00-1848-11eb-8cc2-f4559342be2e.PNG)
![Unbenannt](https://user-images.githubusercontent.com/72564826/97290258-987d6a00-1848-11eb-8cd0-72092c6ae260.PNG)
![2](https://user-images.githubusercontent.com/72564826/97290259-987d6a00-1848-11eb-8f9a-7d93c0ffa79b.PNG)

##### ADDITIONAL INFORMATION

I assume that either I use the commands wrong or the content of the variable survey_spec is not correctly passed to survey_enable.

**Comment by AnnSopVier** [comment]
I just fixed the bug myself. The solution is, that in serializer.py in the class Meta the model JobTemplate has no field 'survey_spec'. After adding 'survey_spec' manually to the two corresponding places in the code the import of surveys via CLI works just fine.

**Comment by ryanpetrello** [comment]
@AnnSopVier sounds like an opportunity for a pull request?

**Comment by thijsvdn** [comment]
I ran into the same issue, tried adding a survey with both the awx cli tool as well as the job_templates/survey_spec API endpoint. The latter returns a '200 OK', but does not add or update a survey.

I've taken a quick look yesterday evening, I *think* @AnnSopVier is referring to awx/api/serializers.py instead of 'serialyzer.py'. Tried following the provided instructions, which did not fix the problem for me. Granted, could be I just didn't decipher the provided solution properly. I'll give fixing this another shot asap.

**Comment by AnnSopVier** [comment]
Hi sorry for the not to clear solution of mine :) So what I did was I added "'survey_spec' ," to the awx/api/serializers.py file at two places (see screenshot attached).
![Unbe1nannt](https://user-images.githubusercontent.com/72564826/98809986-be953380-241e-11eb-896e-14931085dd0b.PNG)
![Unbenannt](https://user-images.githubusercontent.com/72564826/98809988-bfc66080-241e-11eb-8551-def3189282dd.PNG). Afterwards I was able to import a survey with "awx job_templates create --name "<nameOfTemplate>" --job_type run --inventory "<nameOfInventory>" --project "<nameOfProject>" --playbook "<nameOfPlaybook>" --survey_enabled true --survey_spec @/<pathToJsonSurvey>
![Unbenannddt](https://user-images.githubusercontent.com/72564826/98810415-84786180-241f-11eb-960c-cbd4ba9f2fed.PNG)

In the JsonSurvey  I have a simple survey to be imported (see screenshot attached).
![Unbenadnnt](https://user-images.githubusercontent.com/72564826/98810266-3e230280-241f-11eb-91e4-31ec9dfad4f6.PNG)

(Note the screenshot of the survey is just one of the surveys I import it is not  the corresponding survey of the other screenshot ;))

Also of course you need to make sure that the .json with the survey questions is at the described path and the Inventory, Project. Playbook and so on actually exist.

**Comment by thijsvdn** [comment]
Thanks @AnnSopVier. Can't speak for the AWX CLI client, but my problem with the API seems to be a PEBCAK.. Used '/survey_spec' instead of '/survey_spec/'..

**Comment by jbradberry** [comment]
I think maybe what we should do is add new verbs for operations against the related endpoints: `related_get` or `rget`, `related_create` or `rcreate`, `related_modify` or `rmodify`
